language: android

notifications:
  email: false

sudo: false

android:
  components:
    - tools
    - build-tools-23.0.2
    - android-23
    - extra-android-m2repository
    - extra-android-support
  licenses:
    - 'android-sdk-preview-license-52d11cd2'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'

before_install:
 - chmod +x gradlew

script:
  - ./gradlew assembleRelease

deploy:
  provider: releases
  api_key:
    secure: f96bf90b55cc70fd24557cd22c2a9016c94b1d1b
  file: app/build/outputs/apk/app-release.apk
  skip_cleanup: false
  on:
    tags: false