language: android
jdk: oraclejdk8

notifications:
  email: false

sudo: false

android:
  components:
    - tools
    - build-tools-23.0.2
    - android-23
    - extra-android-m2repository
    - extra-android-support
  licenses:
    - 'android-sdk-preview-license-52d11cd2'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'

before_install:
 - chmod +x gradlew

script:
  - ./gradlew assembleRelease

before_deploy:
  - mv app/build/outputs/apk/app-release.apk   

deploy:
  provider: releases
  api_key: "58734053ef214dadcfd3eb4deb2ad6274bae12d3"
  file: "app/build/outputs/apk/app-release.apk"
  skip_cleanup: true
  on:
    tags: true